#!/bin/bash

set -e
SCRIPT_DIR=$( cd `dirname $0`; pwd)
PROJ_DIR=$(cd $SCRIPT_DIR/..; pwd)

docker build  -t yogendra/dotfiles-linux-test:latest -f $SCRIPT_DIR/test-dotfiles-linux.Dockerfile $SCRIPT_DIR


docker run --rm -it --name dotfiles-linux-test --hostname dotfile-linux-test -v $PROJ_DIR/.git:/home/ubuntu/.dotfiles.git/ -v $SCRIPT_DIR/dotfiles-init.Linux.sh:/home/ubuntu/dotfiles-init.Linux.sh yogendra/dotfiles-linux-test:latest

