#!/bin/bash

set -e
SCRIPT_DIR=$( cd `dirname $0`; pwd)
PROJ_DIR=$(cd $SCRIPT_DIR/..; pwd)

docker build  -t yogendra/workspace:latest --target stage-3 -f $SCRIPT_DIR/Dockerfile $SCRIPT_DIR

docker push yogendra/workspace:latest



