#!/bin/bash

set -e
SCRIPT_DIR=$( cd `dirname $0`; pwd)
PROJ_DIR=$(cd $SCRIPT_DIR/..; pwd)

docker build  -t yogendra/dotfiles-linux-stage-1:latest --target stage-1 -f $SCRIPT_DIR/Dockerfile $SCRIPT_DIR


docker run --rm -it --name dotfiles-linux-stage-1 --hostname dotfiles-linux-stage-1 -v $PROJ_DIR/.git:/home/ubuntu/.dotfiles.git/ -v $SCRIPT_DIR/dotfiles-init.Linux.sh:/home/ubuntu/dotfiles-init.Linux.sh yogendra/dotfiles-linux-stage-1:latest

