#!/bin/bash

set -e
SCRIPT_DIR=$( cd `dirname $0`; pwd)
PROJ_DIR=$(cd $SCRIPT_DIR/..; pwd)

docker build  -t yogendra/dotfiles-linux-stage-3:latest --target stage-3 -f $SCRIPT_DIR/Dockerfile $SCRIPT_DIR

docker run --rm -it --name dotfiles-linux-stage-3 --hostname dotfiles-linux-stage-3 yogendra/dotfiles-linux-stage-3:latest

