#!/bin/bash

set -e
SCRIPT_DIR=$( cd `dirname $0`; pwd)
PROJ_DIR=$(cd $SCRIPT_DIR/..; pwd)

docker build  -t yogendra/dotfiles-linux-stage-2:latest --target stage-2 -f $SCRIPT_DIR/Dockerfile $SCRIPT_DIR

docker run --rm -it --name dotfiles-linux-stage-2 --hostname dotfiles-linux-stage-2 yogendra/dotfiles-linux-stage-2:latest

